#base "../resource/scheme/Colors.res"
#base "../resource/scheme/Fonts.res"
#base "../resource/scheme/Symbols.res"
#base "../resource/scheme/Borders.res"
#base "../scripts/crosshairs/fonts/ClientScheme_Crosshairs.res"